### ISSUE TITLE
display 2 digits for single value

### ISSUE THREAD

**Issue by Wonkavator** [thomasloven/lovelace-time-input-row#1]
Hey there, thanks for this work. I was looking for a more compact way for time selection.
Just wondering if it would be a big effort to display 2 digits for a single number value.

How to reproduce:
entering 10:20 -> results in 10:20

entering 10:02 -> results in 10:2 -> expected result -> 10:02

entering 09:20 -> results in 9:20 -> expected result -> 09:20

Let me know if I can give support :)

Cheers

**Comment by thomasloven** [comment]
This is up to the home-assistant implementation of paper-time-input, and unfortuntely nothing I can do anything about now. I noticed it works a bit intermittently when you set the time in the more-info dialog of an input_datetime as well...

**Comment by thomasloven** [comment]
Turns out I was wrong.
